language: python
python:
  - 3.6
cache: pip

# Remove Google's default boto configuration
before_install:
  - sudo rm -f /etc/boto.cfg

env:
  # AWS keys for user travis-ci
  global:
    - secure: bZptls6SNQlG12I3G260/jNPV8tebOqLWwf+HWgj0Wwp7EvbUG/6ul5n0PwMn9C/PtecuNUMvrTg9v0E9FhbkpKVCaTZzcaqSNMq7yVnhVB1Wd+oRzQGjk+IvMJ5N6atfcdap55GZAqCATgYcmbQ6BGhl+1rKjDeAvuv61W0pmRBBhzKb8r65Xmeqxc9vXN0yTPm+MJpT46tuPhWbKo1maetNN2RaLWVv8/mAtuf3qkPz5DLE3p9qYiI5534ZX+j1fyMytRzqNJhdV1uCD7pqGVYJ/oH/4Rcg6mYgSOtEjOhBkmp5Ju5cNn0APA35vCx97kuza60e9WM1cnZRJ9cZVt+hVm9zN+VAoGyIi+xJt4Fkhop91XMT+2HL+tBICyRt7SBPqTSKuPTvaTyl0f9xeyXpCmUChYhO0FKsvyd+YDYi2vzcRDAfrZMny/+a9CXYMt/5Mg4Ogzr42zlaenk/Yg1hZHXCSggcOdWhphfEzRI+nMOl0rvq5JrcfvcyfFIystScdolE53yluBXgll89DXJiiqunBSKls0CrbzID5EjjBmXc4339YxPYQ2AMjziaHH6Son7c09/l8Jzl2o0KAesEnIByJ0iLFLuD0zf24qCcaUuBcRPzQFOa+prtt9F8nmPnEMUD5a6yRauDK594LcqOZnXkUxd9rnLLuiO3ZI=
    - secure: jwT9BzITKED1xbMPj7RW7k5pd8Q89cGbX0CBnHkSJbiSBEN1/yWZ8MWEtTz/PJMi7IN3kHRg5UsZDYfPhF8ROt+8YZ8g0mpVRmwEycVVK0RFOHYV7318EMWkdWeC+NPeMHpwmkEYnf3/56CVpUiqdUd1qi+r+UrBC4v82MGHQI4vEFOkLxHLn9mw2dvS6REXDpAIPqPZO0xGHB9tuhtPxj44Raf41+/xmkduv30wFVwsDvQ7n3EzzWkS0yNXZsATg4f2GAEY8lwPZPG69MsU28Woux6efmEHLRDfpRGrAnH2D/bIVae5BBU6qaRWXAx8/Q0CNjh+KFd986hKXO+2GX4Uk+bismhlDXkMxgF0cDOCn6w3Kqcjgz+eGNFY52d9nooUdyZrwVNeqXfeeN5+vrWD0ByawxBa1UhKOqmI9gCaKShdwIXoU0nHEuvn5YgVO3kkUx3F+c/B1JEMKqEVPKUb4gCJUCujLlP9B1MoZgIni/dgnbrPrPcKiGIrOZo1s8wmnLf/FYTmcD4hj0CIQZdoO8Qex3D9A7J06bZccSS0pQMDgvCKGcDCBJcDLNtJmEF3+Mr8tiq78O6D664nfKnTryXohQ+tO15NZ7Q+2VBddNUTZOB/O3FdwPtfAZM/YxjTZsuF+KH7kNBs838C1OsqqKRMHZLcy2IdMer7HBQ=

#script: cd $TEST_DIR && pip install -r requirements.txt && pytest --ignore=integrationTests

jobs:
  include:
    - stage: unit_tests
      env: TEST_DIR=stasis-server
      install:
        - cd $TEST_DIR
        - pip install -r requirements.txt
      script: pytest tests

    - stage: sls_test_deployment
      env: TEST_DIR=stasis-server
      install:
        - cd $TEST_DIR
        - npm install -g serverless
        - npm install serverless-domain-manager serverless-python-requirements
      script: sls deploy -s test

    - stage: integration_tests
      env: TEST_DIR=stasis-server
      script:
        - cd $TEST_DIR
        - pytest integrationTests

    - stage: sls_prod_deployment
      env: TEST_DIR=stasis-server
      script:
        - cd $TEST_DIR
        - sls deploy -s prod
