SERVICE = "stasis-service"
MESSAGE_BUFFER = 10
SECURE_CARROT_RUNNER = 'secure-carrot-runner'
SECURE_CARROT_AGGREGATOR = 'secure-carrot-aggregator'
SECURE_CARROT_STEAC = 'secure-carrot-steac'
MAX_FARGATE_TASKS_BY_SERVICE = {
    SECURE_CARROT_RUNNER: 90,
    SECURE_CARROT_AGGREGATOR: 10
}
SINGULAR_FARGATE_SERVICES = [
    SECURE_CARROT_STEAC
]
MAX_FARGATE_TASKS = sum(MAX_FARGATE_TASKS_BY_SERVICE.values())