#python run_merger.py ~/Desktop/teddy/positive/shipment-4/fixed-sh4-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-5/fixed-sh5-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-6/fixed-sh6-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-7/fixed-sh7-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-9/fixed-sh9-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-10/fixed-sh10-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-11/fixed-sh11-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-12/fixed-sh12-files-pos-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-13/fixed-sh13-files-pos-results-norepl.xlsx

python run_merger.py ~/Desktop/teddy/negative/shipment-1/fixed-sh1-files-neg-results-norepl.xlsx
python run_merger.py ~/Desktop/teddy/negative/shipment-3/fixed-sh3-files-neg-results-norepl.xlsx
python run_merger.py ~/Desktop/teddy/negative/shipment-4/fixed-sh4-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-5/fixed-sh5-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-6/fixed-sh6-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-7/fixed-sh7-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-9/fixed-sh9-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-10/fixed-sh10-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-11/fixed-sh11-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-12/fixed-sh12-files-neg-results-norepl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-13/fixed-sh13-files-neg-results-norepl.xlsx

python run_merger.py ~/Desktop/teddy/positive/shipment-1/fixed-sh1-files-pos-results-repl.xlsx
python run_merger.py ~/Desktop/teddy/positive/shipment-3/fixed-sh3-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-4/fixed-sh4-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-5/fixed-sh5-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-6/fixed-sh6-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-7/fixed-sh7-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-9/fixed-sh9-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-10/fixed-sh10-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-11/fixed-sh11-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-12/fixed-sh12-files-pos-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/positive/shipment-13/fixed-sh13-files-pos-results-repl.xlsx

#python run_merger.py ~/Desktop/teddy/negative/shipment-1/fixed-sh1-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-3/fixed-sh3-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-4/fixed-sh4-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-5/fixed-sh5-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-6/fixed-sh6-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-7/fixed-sh7-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-9/fixed-sh9-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-10/fixed-sh10-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-11/fixed-sh11-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-12/fixed-sh12-files-neg-results-repl.xlsx
#python run_merger.py ~/Desktop/teddy/negative/shipment-13/fixed-sh13-files-neg-results-repl.xlsx
